const books = [// mock data
  {
    id: '1',
    name: 'buku b',
    year: '2003',
    author: 'Anam',
    summary: 'Buku ini mengandung kisah sedih',
    publisher: 'Karya Abadi',
    pageCount: 90,
    readPage: 23,
    reading: false,
  },
  {
    id: '2',
    name: 'buku c',
    year: '2021',
    author: 'Anam',
    summary: 'Buku ini ',
    publisher: 'Gramedia',
    pageCount: 900,
    readPage: 22,
    reading: false,
  },
  {
    id: '4',
    name: 'buku d',
    year: '2003',
    author: 'Budi bro',
    summary: 'Buku ini mengandung unsur kekerasan',
    publisher: 'Karya Abadi',
    pageCount: 432,
    readPage: 53,
    reading: true,
  },
  {
    id: '5',
    name: 'tessss',
    year: '2003',
    author: 'Anam dong',
    summary: 'Buku ini mengandung kisah sedih',
    publisher: 'Karya Abadi',
    pageCount: 90,
    readPage: 23,
    reading: false,
  },
  {
    id: '6',
    name: 'AYIIIOOO',
    year: '2003',
    author: 'Anam',
    summary: 'Buku ini mengandung kisah sedih',
    publisher: 'Karya Abadi',
    pageCount: 90,
    readPage: 23,
    reading: false,
  },
  {
    id: '7',
    name: 'HALOOO',
    year: '1903',
    author: 'Anonim',
    summary: 'Buku ini mengandung kisah sedih',
    publisher: 'Karya Abadi',
    pageCount: 90,
    readPage: 90,
    reading: true,
  },
];

module.exports = books;
